In [1]:
! pip install numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
lst = [1,2,3,4]
arr = np.array(lst)

In [5]:
lst

[1, 2, 3, 4]

In [6]:
lst
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr = np.array([1,3,4,5,77,8,5])


In [9]:
arr = np.array([range(1,20)])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr = np.arange(1,21)

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
arr = np.zeros([1,21])

In [14]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]])

In [15]:
arr = np.zeros((5,10))


In [16]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:

print(arr.ndim)


2


In [18]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np


In [20]:
arr = np.linspace(1,10,4)

In [21]:
arr

array([ 1.,  4.,  7., 10.])

In [22]:
arr =np.random.randint(1,5,10)

In [23]:
arr

array([2, 2, 1, 4, 1, 4, 1, 4, 3, 2], dtype=int32)

In [24]:
arr = np.random.randint(1,5,(5,6))

In [25]:
arr


array([[2, 4, 2, 2, 2, 1],
       [1, 2, 2, 4, 1, 1],
       [1, 2, 1, 1, 3, 2],
       [4, 4, 1, 3, 1, 4],
       [3, 1, 3, 4, 4, 2]], dtype=int32)

In [26]:
np.random.random(10)  #genrating random by using random 

array([0.84974853, 0.65610712, 0.621915  , 0.59784043, 0.79751151,
       0.01605557, 0.60149862, 0.07864286, 0.67540244, 0.14990979])

In [27]:
np.random.random((10,3))      #2d array

array([[0.00652034, 0.61200552, 0.11459506],
       [0.11531075, 0.35863153, 0.56232555],
       [0.37586869, 0.20228622, 0.36441455],
       [0.74104838, 0.99362373, 0.39882877],
       [0.53571352, 0.76881552, 0.56281158],
       [0.64740198, 0.55821441, 0.10184428],
       [0.1588574 , 0.08445176, 0.01629613],
       [0.64191917, 0.35279941, 0.84693829],
       [0.41680557, 0.07158244, 0.87192318],
       [0.81033509, 0.2045423 , 0.30749059]])

In [28]:
arr=np.arange(60).reshape(12,5)

In [29]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [30]:
arr.ndim    #(dimensio)
arr.shape  #(row and column)
arr.dtype  # (data type batataa h)
arr.size    #(size batat h )

60

In [31]:
print("number of dim:",arr.ndim)                    #(dimensio)
print("shape of array:-",arr.shape)  #(row and column)
print("datatypes of array ",arr.dtype)  # (data type batataa h)
print("size of arraey :-",arr.size)

number of dim: 2
shape of array:- (12, 5)
datatypes of array  int64
size of arraey :- 60


In [32]:
lst = ([1,2,3],[4,5,6])
lst

([1, 2, 3], [4, 5, 6])

In [33]:
arr = np.array(lst)      # list ko arr m change krne lk liye 
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr = np.arange(60).reshape(12,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [36]:
arr.shape

(12, 5)

In [37]:
arr.T                 #Transpose

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [38]:
#a = arr.transpose()
# arr

In [39]:
#a

In [40]:
#b= arr.size


In [41]:
c = arr.dtype
c

dtype('int64')

In [42]:
arr = ([0,0])
arr

[0, 0]

In [43]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [44]:
arr[0,0]

np.int64(0)

In [45]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [47]:
arr[5:7,3:5]

array([[28, 29],
       [33, 34]])

In [48]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [49]:
arr[-1,-1]
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [50]:
print("number of dim:",arr.ndim)                    #(dimensio)
print("shape of array:-",arr.shape)  #(row and column)
print("datatypes of array ",arr.dtype)  # (data type batataa h)
print("size of arraey :-",arr.size)

number of dim: 2
shape of array:- (12, 5)
datatypes of array  int64
size of arraey :- 60


# 3 - d array

In [51]:
#3 -d array
 
arr = np.arange(60).reshape(3,10,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [52]:
arr = np.arange(225).reshape(5,15,3)
arr

# 5 is table 
# 15 is row      and multiplication give 225
# 3 is colunm

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [53]:
arr[0]         # 1 st table

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [54]:
arr[0][0]       # arr[0,0]        #1st table ka 1st row

array([0, 1, 2])

In [55]:
arr[0][0][0]            #1ST table ka 1st element

np.int64(0)

In [56]:
arr[-1]         #last table of 

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [57]:
arr[0:5,0]     # each table ka  ist row

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [58]:
arr[0:5,0,0]      # each table ka 1st element

array([  0,  45,  90, 135, 180])

In [59]:
arr[0:5,-1,-1]    #eeach last 

array([ 44,  89, 134, 179, 224])

In [60]:
arr[0:5,2:4]   # each table ka 3 4 row

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [61]:
arr[0:5,:,1:3]  #each column ka 2 3 column

array([[[  1,   2],
        [  4,   5],
        [  7,   8],
        [ 10,  11],
        [ 13,  14],
        [ 16,  17],
        [ 19,  20],
        [ 22,  23],
        [ 25,  26],
        [ 28,  29],
        [ 31,  32],
        [ 34,  35],
        [ 37,  38],
        [ 40,  41],
        [ 43,  44]],

       [[ 46,  47],
        [ 49,  50],
        [ 52,  53],
        [ 55,  56],
        [ 58,  59],
        [ 61,  62],
        [ 64,  65],
        [ 67,  68],
        [ 70,  71],
        [ 73,  74],
        [ 76,  77],
        [ 79,  80],
        [ 82,  83],
        [ 85,  86],
        [ 88,  89]],

       [[ 91,  92],
        [ 94,  95],
        [ 97,  98],
        [100, 101],
        [103, 104],
        [106, 107],
        [109, 110],
        [112, 113],
        [115, 116],
        [118, 119],
        [121, 122],
        [124, 125],
        [127, 128],
        [130, 131],
        [133, 134]],

       [[136, 137],
        [139, 140],
        [142, 143],
        [145, 146],
        [148, 

In [62]:
arr[0:5,-1,-1]       # each  table ka last elemenmt

array([ 44,  89, 134, 179, 224])

In [63]:
arr[0:5,0:1,0:1]     #each table ka each column ka 1st element

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [64]:
print("number of dim:",arr.ndim)                    #(dimensio)
print("shape of array:-",arr.shape)  #(row and column)
print("datatypes of array ",arr.dtype)  # (data type batataa h)
print("size of array:-",arr.size)

number of dim: 3
shape of array:- (5, 15, 3)
datatypes of array  int64
size of array:- 225


In [65]:
arr[0,0,0] = 100
arr

array([[[100,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [66]:
arr[0:5,0]=100
arr

array([[[100, 100, 100],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[100, 100, 100],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[100, 100, 100],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
arr1=np.array([6,7,8,9])
arr2 = np.array([1,2,3,4])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1* +arr2)
print(arr1/arr2)
print(arr1//arr2)


[ 7  9 11 13]
[5 5 5 5]
[ 6 14 24 36]
[ 6 14 24 36]
[6.         3.5        2.66666667 2.25      ]
[6 3 2 2]


In [68]:
arr1=np.array([10,20,30,40])
arr2=np.array([4,2,8,6])
print("array1:",arr1)
print("arrary 2:",arr2)



array1: [10 20 30 40]
arrary 2: [4 2 8 6]


In [69]:
arr2.sort()
print(arr2)       # print()use krna pdega

[2 4 6 8]


conversion of 1d into 3 d

In [70]:
a = np.arange(225)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [71]:
a = a.reshape(5,15,3)
a

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11