In [ ]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
print("heloo kaise ho")

heloo kaise ho


In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.4.6'

In [ ]:
lst = list(range(1,20))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
type(lst)

list

In [ ]:
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array([1,2,3,44,3])
arr

array([ 1,  2,  3, 44,  3])

In [ ]:
arr = np.array(range(1,20))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr= np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
print(arr.ndim)

1


In [ ]:
arr = np.zeros((5,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
print(arr.ndim)

2


In [ ]:
arr = np.linspace(1,10,5)    #1 is strating point ,10 is range(float number bhi a skte s) and 5elemnt are reuired
arr


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.linspace(2,30,7)
arr

array([ 2.        ,  6.66666667, 11.33333333, 16.        , 20.66666667,
       25.33333333, 30.        ])

In [ ]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr = arr.reshape(3,10)      #reshapeing the one - d array to 2-d array
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr = arr.reshape(6,5)           #multiply krne p range k equal ana chaye
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a= np.random.randint(1,3,10)
a
# 1 is starting point
# 3 is range   no float number
#10 is no of elemnt we want
#

array([2, 2, 2, 1, 2, 2, 2, 1, 1, 1], dtype=int32)

In [ ]:
np.random.randint(1,5,(5,6))   # 1 is strating,5 is range and(5,6) is elment is w want

array([[4, 4, 1, 1, 2, 4],
       [1, 2, 2, 4, 3, 1],
       [1, 4, 3, 2, 1, 1],
       [4, 1, 2, 2, 3, 3],
       [4, 3, 1, 2, 1, 3]], dtype=int32)

In [ ]:
arr = np.random.random(10)
arr
#by using randoom random flaot number can also be include


array([0.05943964, 0.86722964, 0.58200302, 0.73156946, 0.50195952,
       0.8575243 , 0.59725034, 0.32173963, 0.20361715, 0.95320841])

In [ ]:
arr = np.random.random((10,3))
arr

array([[0.78276335, 0.19709627, 0.23647694],
       [0.38461314, 0.75708762, 0.3443647 ],
       [0.38341691, 0.62002615, 0.06561398],
       [0.63828456, 0.81172206, 0.11017023],
       [0.04453856, 0.07474046, 0.92277195],
       [0.63679053, 0.44117896, 0.78724268],
       [0.19397571, 0.14197405, 0.87640617],
       [0.13035921, 0.41539358, 0.45098725],
       [0.39482244, 0.24358328, 0.81493994],
       [0.30459644, 0.75740183, 0.74243613]])

In [ ]:
arr= np.arange(3,11).reshape(2,4)
arr
#we can create array and turn it into 2d at same time

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
arr = np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
print("number of dimension:-",arr.ndim)
print("shape of array:-",arr.shape)
print("data type of item:-",arr.dtype)
print("size of array:-",arr.size)

number of dimension:- 2
shape of array:- (5, 6)
data type of item:- int64
size of array:- 30


In [ ]:
lst =[[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [ ]:
arr = np.array(lst)
arr
#list is convert into 2d array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.arange(0,60).reshape(10,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [ ]:
arr.shape

(10, 6)

In [ ]:
arr=arr.T     #Transpose the array
arr

array([[ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55],
       [ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56],
       [ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57],
       [ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58],
       [ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59]])

In [ ]:
a = arr.transpose()
a

array([[ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55],
       [ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56],
       [ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57],
       [ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58],
       [ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59]])

In [ ]:
arr[0,0]
#fisrt 0 means row
#second 0 means colunm

np.int64(0)

In [ ]:
arr[0][0]    # ek hi bat [0,0]

np.int64(0)

In [ ]:
arr[0][9]

np.int64(54)

In [ ]:
#last ko niklane k liye
arr[5,9]

np.int64(59)

In [ ]:
arr[-1,-1]   #2nd way

np.int64(59)

In [ ]:
arr[5,-1]

np.int64(59)

In [ ]:
arr[-1,9]

np.int64(59)

In [ ]:
arr[2:4,3:]

array([[20, 26, 32, 38, 44, 50, 56],
       [21, 27, 33, 39, 45, 51, 57]])

In [ ]:
arr = np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[11,4]

np.int64(59)

In [ ]:
#16,17,22,23
arr[3:5,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

In [ ]:
#41 to53
arr[8:11,1:4]

array([[41, 42, 43],
       [46, 47, 48],
       [51, 52, 53]])

In [ ]:
#onlyn one colun
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [ ]:
# changing an element
arr[-1,-1]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [ ]:
print("number of dimension:-",arr.ndim)
print("shape of array:-",arr.shape)
print("data type of item:-",arr.dtype)
print("size of array:-",arr.size)

number of dimension:- 2
shape of array:- (10, 6)
data type of item:- int64
size of array:- 60
